container running, not communicating

diff --git a/Bankensystem/Dockerfile_stockMarket b/Bankensystem/Dockerfile_stockMarket
--- a/Bankensystem/Dockerfile_stockMarket
+++ b/Bankensystem/Dockerfile_stockMarket
@@ -5,11 +5,19 @@ FROM gcc:latest
 WORKDIR /app
 
 # Copy the current directory contents into the container at /app
-COPY StockMarket /app/StockMarket
+COPY /StockMarket /app/StockMarket
 COPY /Stock/ /app/Stock
 
+# install stuff
+# eux
+# -e: exit imme­di­ate­ly if a com­mand returns a non-zero status
+# -u: treat unset vari­ables and para­me­ters oth­er than the spe­cial para­me­ters ‘@’ or ‘*’ as an error 
+# -x: print a trace of sim­ple commands
+RUN set -eux
+RUN dir -s
+
 # Compile the C++ program
-RUN g++ -std=c++11 /app/StockMarket/stockMarket.cpp -o /app/StockMarket/StockMarket
+RUN g++ -std=c++11 /app/StockMarket/stockMarket.cpp -o /app/StockMarket/stockMarket
 
 # Set the command to run when the container starts
-CMD [".app/StockMarket/StockMarket"]
+CMD ["./StockMarket/stockMarket"]
